#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright © 2015 Michal Čihař <michal@cihar.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
import argparse
import sys
import json
import os.path
import urllib2
import unicodedata
import re
from xdg.BaseDirectory import save_config_path

SF_URL = 'https://sourceforge.net/p/{0}/{1}/{2}/'
BODY_TEMPLATE = u'''{body}

---
* **Original URL**: {url}
* **Original author**: {author}
{attachments}
'''
POST_TEMPLATE = u'''{body}

---
* **Original author**: {author}
{attachments}
'''
LABEL_MAP = {
    'Bugs': 'bug',
    'Feature Requests': 'enhancement',
    'Patches': 'patch',
    'Translations': 'translation',
    'Support Requests': 'question',
}
TILDES = re.compile('^~~~+$')
USER_MAP = {
    'nijel': 'nijel',
    'madhuracj': 'madhuracj',
    'lem9': 'lem9',
    'atul5': 'zixtor',
    'ibennetch': 'ibennetch',
    'tithugues': 'Tithugues',
    'chirayu45': 'D-storm',
    'smita786': 'smita786',
}


class StatusStorage(object):
    def __init__(self):
        self.path = os.path.join(
            save_config_path('sf2gh'),
            'status.json'
        )
        self.data = {}

    def load(self):
        if os.path.exists(self.path):
            with open(self.path, 'r') as handle:
                self.data = json.load(handle)
        if 'tickets' not in self.data:
            self.data['tickets'] = {}

    def save(self):
        with open(self.path, 'w') as handle:
            json.dump(self.data, handle, indent=2)

    def clean(self):
        self.data = {}
        self.save()


class GitHubImport(object):
    def __init__(self, args):
        self.status = StatusStorage()
        self.status.load()
        self.handle = args.import_handle
        self.token = args.token
        self.repo = args.repo
        self.verbose = args.verbose
        self.retry_failed = args.retry_failed
        self.sf_project = args.sf_project
        self.mount_point = None
        self.tracker_label = None
        self.closed_states = None
        self.milestones = None

    def api(self, url, data=None):
        if data:
            data = json.dumps(data)
        if 'https://' not in url:
            url = 'https://api.github.com/repos/{0}/{1}'.format(
                self.repo, url
            )
        request = urllib2.Request(
            url,
            data,
            {
                'Authorization': 'token {0}'.format(self.token),
                'Accept': 'application/vnd.github.golden-comet-preview+json',
            },
        )
        try:
            handle = urllib2.urlopen(request)

            result = json.load(handle)
        except urllib2.HTTPError as error:
            print error.hdrs
            print error.fp.read()
            raise

        if 'Link' in handle.headers:
            for item in handle.headers['Link'].split(','):
                url, rel = item.split(';')
                url = url.strip()
                rel = rel.strip()
                if rel == 'rel="next"':
                    result += self.api(url[1:-1])
        return result

    def create_milestone(self, title):
        data = {
            'title': title,
            'state': 'closed',
            'description': 'Imported from SourceForge.net',
        }
        response = self.api(
            'milestones',
            data
        )
        self.milestones[response['title']] = response['number']
        if self.verbose:
            print 'Created milestone {0}'.format(title)

    def format_time(self, timestamp):
        return '{0}Z'.format(timestamp.replace(' ', 'T'))

    def is_textile(self, timestamp):
        """Detect if textile renderer will be used on github

        It depends on creation timestamp.
        """
        ts = int(timestamp.split()[0].replace('-', ''))
        return ts < 20090421

    def format_url(self, url, textile):
        if textile:
            return '"{0}":{1}'.format(
                url, url
            )
        else:
            return url

    def clean(self):
        self.status.clean()

    def check(self):
        for url in self.status.data['tickets']:
            data = self.status.data['tickets'][url]
            if 'import_response' not in data:
                continue

            if data['import_response']['status'] == 'pending':
                data['import_response'] = self.api(data['import_response']['url'])
                self.status.save()

            if data['import_response']['status'] not in ('pending', 'imported'):
                print 'Error in importing:', url
                print data['import_response']

    def mapping(self):
        for url in self.status.data['tickets']:
            data = self.status.data['tickets'][url]
            if 'import_response' not in data:
                continue

            if data['import_response']['status'] == 'imported':
                print '{0} {1}'.format(
                    url,
                    data['import_response']['issue_url'].replace(
                        'https://api.github.com/repos/',
                        'https://github.com/'
                    )
                )

    def get_tracker_label(self, data):
        mount = data['tracker_config']['options']['mount_label']
        return LABEL_MAP[mount]

    def get_assignee(self, ticket):
        if ticket['assigned_to'] in USER_MAP:
            return USER_MAP[ticket['assigned_to']]
        return None

    def process(self):
        data = json.load(self.handle)

        # Tracker mount point
        self.mount_point = data['tracker_config']['options']['mount_point']
        self.tracker_label = self.get_tracker_label(data)
        self.closed_states = data['closed_status_names'].split()

        self.milestones = {
            m['title']: m['number'] for m in
            self.api('milestones?state=all')
        }

        for ticket in data['tickets']:
            result = self.process_ticket(ticket)
            if result:
                self.status.save()

    def is_closed(self, ticket):
        status = ticket['status']
        if status in self.closed_states:
            return True

        # Mark resolved as closed as well
        if status == 'resolved':
            return True

        # Should not be used at all
        if 'pending' in status:
            return True

        return False

    def should_skip(self, url):
        if url not in self.status.data['tickets']:
            return False

        if 'import_response' not in self.status.data['tickets'][url]:
            return False

        if not self.retry_failed:
            return True

        response = self.status.data['tickets'][url]['import_response']
        if response['status'] in ('pending', 'imported'):
            return True

        return False

    def process_ticket(self, ticket):
        url = SF_URL.format(
            self.sf_project, self.mount_point, ticket['ticket_num']
        )

        if self.should_skip(url):
            if self.verbose:
                print 'Already processed:', url
            return False

        # This one causes server error
        IGNORED = (
            'https://sourceforge.net/p/phpmyadmin/bugs/2669/',
        )

        if url in IGNORED:
            return False

        labels = [
            self.tracker_label,
        ]

        if 'duplicate' in ticket['status']:
            labels.append('duplicate')
        elif 'invalid' in ticket['status']:
            labels.append('invalid')
        elif 'out-of-date' in ticket['status']:
            labels.append('invalid')
        elif 'works-for-me' in ticket['status']:
            labels.append('invalid')
        elif 'wont-fix' in ticket['status']:
            labels.append('wontfix')

        summary = ticket['summary'].replace('\\"', '"').replace("\\'", "'")
        milestone = None
        if summary.startswith('(in ') or summary.startswith('(ok '):
            milestone, summary = summary.split(')', 1)
            # Remove prefix and possible suffix (eg. 2.11-dev, or 2.11.3-rc1)
            # or (ok 2.5.2, new FAQ)
            milestone = milestone[4:].split(',')[0].split('-')[0].strip()
            if milestone.endswith('dev'):
                milestone = milestone[:-3]
        summary = summary.strip()

        textile = self.is_textile(ticket['created_date'])

        issue = {
            'title': summary,
            'body': BODY_TEMPLATE.format(
                url=self.format_url(url, textile),
                body=self.process_body(ticket['description']),
                author=ticket['reported_by'],
                attachments=self.process_attachments(ticket, textile),
            ),
            'created_at': self.format_time(ticket['created_date']),
            'closed': self.is_closed(ticket),
            'labels': labels,
        }
        assignee = self.get_assignee(ticket)
        if assignee:
            issue['assignee'] = assignee

        if milestone:
            if milestone not in self.milestones:
                self.create_milestone(milestone)
            issue['milestone'] = self.milestones[milestone]

        comments = [
            self.process_comment(comment)
            for comment in ticket['discussion_thread']['posts']
        ]

        request = {'issue': issue, 'comments': comments}

        if self.verbose:
            print json.dumps(request, indent=2)

        response = self.api('import/issues', request)
        assert response['status'] == 'pending'

        if self.verbose:
            print json.dumps(response, indent=2)

        self.status.data['tickets'][url] = {
            'import_response': response,
        }
        return True

    def process_body(self, description):
        # Normalize unicode
        description = unicodedata.normalize('NFC', description)
        # SourceForge.net special markup
        description = description.replace(
            '\\*', '*'
        ).replace(
            '\\#', '#'
        ).replace(
            '\\!', '!'
        ).replace(
            '\\_', '_'
        ).replace(
            '\\`', '`'
        ).replace(
            '\\]', ']'
        ).replace(
            '\\[', '['
        ).replace(
            '\\(', '('
        ).replace(
            '\\)', ')'
        ).replace(
            '\\\\', '\\'
        )
        description = TILDES.sub('```', description)
        lines = description.splitlines()

        # Reformat initial state change texts
        for i, line in enumerate(lines):
            if line.startswith('- **'):
                lines[i] = u'* {0}'.format(line[1:])
            else:
                break

        # Remove initial - escaping
        for i, line in enumerate(lines):
            if line.startswith('\\-'):
                lines[i] = line[1:]

        return '\n'.join(lines)

    def process_comment(self, post):
        textile = self.is_textile(post['timestamp'])
        return {
            'created_at': self.format_time(post['timestamp']),
            'body': POST_TEMPLATE.format(
                body=self.process_body(post['text']),
                author=post['author'],
                attachments=self.process_attachments(post, textile),
            ),
        }

    def process_attachments(self, post, textile):
        result = []

        if ('custom_fields' in post and
                '_milestone' in post['custom_fields'] and
                self.mount_point in ('support-requests', 'bugs')):
            result.append(
                '* **Found in version**: {0}'.format(
                    post['custom_fields']['_milestone']
                )
            )
        for attachment in post['attachments']:
            result.append(
                '* **Attachment**: {0}'.format(
                    self.format_url(attachment['url'], textile)
                )
            )
        return '\n'.join(result)


def get_parser():
    parser = argparse.ArgumentParser(
        description='SourceForge.net to GitHub issue import',
    )

    # General parameters
    parser.add_argument(
        '--token',
        help=(
            'GitHub OAuth token, get it at ' +
            'https://github.com/settings/tokens'
        ),
        required=True,
    )
    parser.add_argument(
        '--repo',
        help='GitHub repository where to import',
        required=True
    )
    parser.add_argument(
        '--sf-project',
        help='Name of SourceForge.net project, eg. phpmyadmin',
        required=True
    )
    parser.add_argument(
        '--verbose',
        help='Verbose processing',
        action='store_true',
    )
    parser.add_argument(
        '--retry-failed',
        help='Retry failed imports',
        action='store_true',
    )

    # Actions
    group = parser.add_mutually_exclusive_group(
        required=True
    )
    group.add_argument(
        '--import',
        help='SourceForge.net tracker backup json',
        type=argparse.FileType('r'),
        dest='import_handle'
    )
    group.add_argument(
        '--check',
        help='Check status of previous imports',
        action='store_true'
    )
    group.add_argument(
        '--mapping',
        help='Displays mapping of SourceForge URLs to GitHub ones',
        action='store_true'
    )
    group.add_argument(
        '--clean',
        help='Clean local storage of previous imports',
        action='store_true'
    )

    return parser


def main():
    parser = get_parser()
    args = parser.parse_args(sys.argv[1:])
    importer = GitHubImport(args)
    if args.clean:
        importer.clean()
    elif args.check:
        importer.check()
    elif args.mapping:
        importer.mapping()
    else:
        importer.process()


if __name__ == "__main__":
    main()
